server:
  port: 8899
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com/mapleooooly/cloud-config.git
          ###搜索目录
          search-paths:
            - cloud-config
      #读取分支
      label: master

eureka:
  client:
    service-url:
      de
